source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '~> 7.1.1'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'bootsnap', require: false
gem 'excon'
gem 'rack-cors', :require => 'rack/cors'
gem "active_model_serializers", "~> 0.10.0"
gem "bcrypt", "~> 3.1", ">= 3.1.18"

group :development, :test do
  gem "pry"
  gem 'debug', platforms: %i[mri windows]
  gem 'dotenv-rails'
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", ">= 2.24.0", require: false
  gem "solargraph", require: false
end
